### ISSUE TITLE
Following PR breaks session

### ISSUE THREAD

**Issue by Plork** [sierpinski/Blitz#15]
Once you click on "handle request" it opens a new tab and it breaks authentication. The page loads but all content is "blank".

The moment I click on "something" I get:

401: 401: error
TFS.WebApi.Exception: 401: error
    at k (http://tfs.local:8080/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/corejs?v=ITI0eYHCCehqqjk6JTyPaR5R793ETLoY2_Lqz191Pyo1:64:375)
    at http://tfs.local:8080/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/corejs?v=ITI0eYHCCehqqjk6JTyPaR5R793ETLoY2_Lqz191Pyo1:64:2955
    at d (http://tfs.local:8080/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/corejs?v=ITI0eYHCCehqqjk6JTyPaR5R793ETLoY2_Lqz191Pyo1:64:635)
    at http://tfs.local:8080/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/corejs?v=ITI0eYHCCehqqjk6JTyPaR5R793ETLoY2_Lqz191Pyo1:64:2888
    at l (http://tfs.local:8080/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/q.js:27:8122)
    at http://tfs.local:8080/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/q.js:27:8348
    at t.when (http://tfs.local:8080/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/q.js:27:3780)
    at t.u.promiseDispatch (http://tfs.local:8080/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/q.js:27:2824)
    at http://tfs.local:8080/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/q.js:27:1649
    at MessagePort.t (http://tfs.local:8080/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/q.js:27:5773)
Session Id: f2ae9b26-30b6-40d4-8d90-4c48a29b7563

Would be cool If i get this to work since the build-in view is WAYY too limited.

**Comment by sierpinski** [comment]
Hey @Plork is this on-premise or VSTS? I have these on-premise issues I've really struggled to fix.

**Comment by Plork** [comment]
Yeah, this is on premise

Op 17 aug. 2016 4:48 p.m. schreef "sierpinski" notifications@github.com:

**Comment by MKenin** [comment]
It's the same for our on-premises server. I can provide more info and test things if you need.

**Comment by sierpinski** [comment]
I've changed the construction of the pull request url and it should now open in the same window when you try to handle the request. If either of you on-prem. could check it out I would appreciate it.

**Comment by sierpinski** [comment]
It's fixed in the latest release!! Finally!!! Feel free to check it out and work those requests!
